fix compileOutput.py script to run on viralflow env
dezordi/IAM_SARSCOV2 pull request #29
Opened 2023-10-10 00:56 UTC by alexandrefreitasdasilva

This PR changes the way of compileOutput.py script runs to work on viralflow env due to some inconsistencies when running inside the container on HPC.

2023-10-10 14:19 UTC, dezordi requested changes
boa, só ajudar o env.yml

2023-10-10 14:19 UTC, dezordi commented on envs/env.yml
> +  - pandas
incluir as versões do pandas e do bipython no env

2023-10-11 19:51 UTC, alexandrefreitasdasilva commented on envs/env.yml
> +  - pandas
Done!

2023-10-11 23:13 UTC, dezordi approved these changes

2023-11-03 13:59 UTC, AMarinhoSN approved these changes

2023-11-03 14:43 UTC, merged